### ISSUE TITLE
1.4 Applying string interpolation

### ISSUE THREAD

**Issue by ishehroze** [ishehroze/angular-six-test#2]
I want to try out the string interpolation feature in angular similar to how it has been shown in the tutorial: https://codecraft.tv/courses/angular/quickstart/string-interpolation/

**Comment by ishehroze** [comment]
~~When trying to execute the following command:~~

```bash
ng serve --open
```

~~I am getting the following output:~~
```
(node:13944) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 10% building modules 3/4 modules 1 active …server\client\index.js?http://0.0.0.0:0node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\webpack\lib\NormalModule.js:386:16)
    at handleParseError (C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\webpack\lib\NormalModule.js:434:10)
    at C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\webpack\lib\NormalModule.js:466:5
    at C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\webpack\lib\NormalModule.js:327:12
    at C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\loader-runner\lib\LoaderRunner.js:373:3        
    at iterateNormalLoaders (C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\loader-runner\lib\LoaderRunner.js:205:4        
    at VirtualFileSystemDecorator.readFile (C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:47:13)
    at processResource (C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders (C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at runLoaders (C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\loader-runner\lib\LoaderRunner.js:365:2)      
    at NormalModule.doBuild (C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\webpack\lib\NormalModule.js:265:3)  
    at NormalModule.build (C:\Users\MISL\OneDrive\Desktop\html-test\angular-six-test\node_modules\webpack\lib\NormalModule.js:412:15) { 
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.6.0
```

~~@mohinur-dev bhai, need help with it~~

Fixed. See [this comment](#issuecomment-2213552919)

**Comment by ishehroze** [comment]
Fixed the openssl unsupported issue by downgrading node version to 16.20.2. Used [nvm](https://github.com/coreybutler/nvm-windows) for installing the specific version.

**Comment by ishehroze** [comment]
@mohinur-dev bhai, please review #3 and close this issue. Feel free to contact me regarding how it worked.
